#!/usr/bin/perl -w

print "Enter numbers from 1-7\n";
chomp(@nums = <STDIN>);
@names = qw(fred betty barney dino wilma pebbles bamm-bamm);
foreach (@nums) {
        print $names[$_ - 1] . "\n";
}




