#!/usr/bin/perl -w

use strict;
use 5.010;

&test();

sub greet{
    


    state @names; 

    for (@_){
        my $current = $_;
    
        if (@names) {
            print "Hi $current! I've seen: @names\n" ;
        } else {
            print "Hi $current! You're the first one here\n";
        }
        push @names, $current;
    }
}


sub test {
    greet("Fred");
    greet("Barney");
    greet("Wilma");
    greet("Betty");
    greet("Bamm-Bamm");
    greet("Pebbles");
}
