#!/usr/bin/perl -w

use strict;


#Write a subroutine name total which returns the toal of a list of numebers.


&testProgram();

sub total {
    
    my $sum;
    foreach (@_){

    $sum += $_;
    }

    return $sum;
}

sub testProgram {

my @fred = qw { 1 3 5 7 9};
my $fred_total = total(@fred);
print "the total of \@fred is $fred_total\n";

print "Enter some numbers on separate lines: ";

my $user_total = total(<STDIN>);
print "the total of \@fred is $user_total\n";


}
